### ISSUE TITLE
Error during build phase fs.createFileAbsolute

### ISSUE THREAD

**Issue by sleipnir** [burrito-elixir/burrito#102]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**:  Linux pop-os 5.18.10-76051810-generic #202207071639~1657252310~21.10~7d5e891 SMP PREEMPT_DYNAMIC Fri J x86_64 x86_64 x86_64 GNU/Linux
**Host CPU**: x86_64

Please run `zig version` in your Burrito project directory and write the version here:
0.12.0-dev.164+7a834e258

Please run `elixir -v` in your Burrito project directory and write the version here:

Erlang/OTP 25 [erts-13.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.0 (compiled with Erlang/OTP 25)
------

### Target

**Host OS**: Linux
**Host CPU**:  x86_64

------

(Describe your issue details here!)
Error on call MIX_ENV=prod mix release

```
----> PHASE: :build
--> Generating wrapper metadata file...
/home/sleipnir/workspaces/eigr/deps/burrito/src/archiver.zig:213:97: error: expected 1 argument, found 2
            const file = try fs.createFileAbsolute(full_file_path, .{ .truncate = true, .mode = @intCast(os.mode_t, file_mode) });
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--> Cleaning up...
--> Burrito failed to wrap up your app! Check the logs for more information.
** (RuntimeError) Wrapper build failed
    (burrito 0.8.0) lib/steps/build/pack_and_build.ex:54: Burrito.Steps.Build.PackAndBuild.execute/1
    (burrito 0.8.0) lib/builder/builder.ex:139: anonymous fn/3 in Burrito.Builder.run_phase/2
    (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.14.0) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.8.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
    (mix 1.14.0) lib/mix/tasks/release.ex:1068: Mix.Tasks.Release.run_steps/1
    (mix 1.14.0) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.0) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

**Comment by Trevoke** [comment]
I ran into the same problem - this is due to a change within zig, it seems. If you use zig 0.10.x this error doesn't happen. I realize this isn't a long-term fix for Burrito, but it may get you going in the short term.

**Comment by doawoo** [comment]
This is in fact a major change Zig has made to the language along with a number of others. It'll take a bit to pick out all the other changes. Sticking to the version defined in the ASDF tool-versions file is the best route for now. But that also introduces issues with Sonoma hosts.

A few others and myself are working on a replacement wrapper for Burrito apps in Rust - eliminating the Zig upkeep for the future.

**Comment by sleipnir** [comment]
Okay guys, thanks a lot for replying. I'm a big believer in Zig, but these compatibility breaks are really annoying.
I will try to downgrade the Zig version
