### ISSUE TITLE
Builds fails on OSX aarch64

### ISSUE THREAD

**Issue by mfeckie** [burrito-elixir/burrito#121]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: OSX
**Host CPU**: Apple Silicon

Please run `zig version` in your Burrito project directory and write the version here:

0.11.0

Please run `elixir -v` in your Burrito project directory and write the version here:

1.15.6
------

### Target

**Host OS**: OSX
**Host CPU**: aarch64 
**Host LibC and Version** gnu

------

Added Burrito to my project as per README.

Config provided :

```elixir

  def releases do
    [
      snappy: [
        steps: [:assemble, &Burrito.wrap/1],
        burrito: [
          targets: [
            macos: [os: :darwin, cpu: :aarch64],
            linux: [os: :linux, cpu: :x86_64]
          ]
        ]
      ]
    ]
  end

```

Run `env MIX_ENV=prod mix release`.  This generates the binary and seems fine.

execute `/Users/dev/snappy/burrito_out/snappy_macos` and it immediately errors

Based on the output, it _looks_ like maybe it's not dealing with the directory `Application Support` (note the space) properly, though I'm just guessing at this point.

```
  ~/dev/snappy   main *1 ?2 ❯ /Users/dev/snappy/burrito_out/snappy_macos                                                                                                                                         55s  02:48:21 pm
sh: /Users/dev/Library/Application: No such file or directory
sh: line 0: exec: /Users/dev/Library/Application: cannot execute: No such file or directory
```

I've used `bakeware` with the same project as an experiment and it builds and executes without an issue.

Happy to contribute to solutions if anyone can tell my why it borking.  Thanks

**Comment by doawoo** [comment]
Does this happen with the `example_cli` application in the repository?
I can't seem to reproduce this on my M1 MacBook Pro, what are the app's mix dependancies?

**Comment by mfeckie** [comment]
Thanks for reply.  I was able to run the example app successfully, so it looks like it's something in my application.  It runs fine as a plain elixir app, but fails when using via burrito.

It's consuming https://github.com/mechanical-orchard/playwright-elixir which tries to open an instance of Chromium and I suspect that's where it's falling over now.

Will have to do more digging to figure out what's different in a burrito package that makes it fail to produce the correct path 🤔
