### ISSUE TITLE
otp_26.2.1_darwin_aarch64_ssl_1.1.1s.tar.gz not built yet

### ISSUE THREAD

**Issue by brendon9x** [burrito-elixir/burrito#125]
Hi,

I would really appreciate a build for above. Output below. 

<img width="1621" alt="Screenshot 2023-12-21 at 20 46 15" src="https://github.com/burrito-elixir/burrito/assets/491483/e6c09c25-9b5a-4b12-81e9-07e91fd3adc6">

🙏

**Comment by doawoo** [comment]
Hello there! 

I recommend you update your current checked out burrito to the one released on Hex.pm -- we updated things to use OpenSSL 3.x and have more universal builds for Linux and MacOS!

**Comment by msutkowski** [comment]
@doawoo is there a list of precompiled binaries somewhere? Every version I've tried so far 404's similar to the image above.

**Comment by msutkowski** [comment]
> @doawoo is there a list of precompiled binaries somewhere? Every version I've tried so far 404's similar to the image above.

https://beammachine.cloud/ 🎉

**Comment by doawoo** [comment]
Just poking this issue for updates :)
Is this all resolved and good to close?

**Comment by doawoo** [comment]
Closing to keep issues clean, lemme know if things still aren't working as expected :)
