### ISSUE TITLE
Bump Req in mix.exs to 0.4

### ISSUE THREAD

**Issue by clayscode** [burrito-elixir/burrito#126]
Please consider updating the Req requirement to 0.4 as 0.3 is a few months out of date at this point. Attempting to use Burrito for a project but can't compile due to dependencies requiring newer versions of Req than currently supported in Burrito.

**Comment by doawoo** [comment]
Thanks for letting me know! I'll bump that dep and get a new release out ASAP 😄

**Comment by doawoo** [comment]
Fixed in the latest release! Thanks for your patience

**Comment by clayscode** [comment]
Thanks! :partying_face:
