### ISSUE TITLE
Failed to fetch a precompiled Erlang (version 26.2.1)

### ISSUE THREAD

**Issue by mmower** [burrito-elixir/burrito#127]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: macOS 13.6.1
**Host CPU**: M2 Max

Please run `zig version` in your Burrito project directory and write the version here:
zig 0.11.0

Please run `elixir -v` in your Burrito project directory and write the version here:
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.16.0 (compiled with Erlang/OTP 26)
------

### Target

**Host OS**: (eg. MacOS 12.3.1 ...)
**Host CPU**: (eg. x86_64, aarch64 ...)
**Host LibC and Version** (eg. gnu/musl x.y.z ...)

OS: darwin
	CPU: x86_64
	Qualifiers: [libc: nil]
	Debug: false

------

➜  rez git:(main) ✗ BUILD_MODE=burrito MIX_ENV=prod mix release
Release rez-1.1.5 already exists. Overwrite? [Yn]
* assembling rez-1.1.5 on MIX_ENV=prod
* skipping runtime configuration (config/runtime.exs not found)
* creating _build/prod/rel/rez/releases/1.1.5/vm.args
-> We couldn't find 7z in your PATH, 7z is required to build Windows releases. They will fail if you don't fix this!
-> Burrito is building target: macos
-> Burrito will build for target:
	OS: darwin
	CPU: x86_64
	Qualifiers: [libc: nil]
	Debug: false
--> PHASE: :fetch
---> Working directory: /var/folders/ds/gmt3n6bn7svbvbqp5jwxgstm0000gn/T/burrito_build_F9DBD96777BA925D
---> Resolving ERTS: {:precompiled, [version: "26.2.1"]}
---> Failed to fetch a precompiled Erlang (version 26.2.1)!
	 Reason: No pre-compiled version matching this combination of platform, arch, and libc was found on our CI system.
---> Cannot resolve ERTS, please check for errors in the log above.
-> Halt requested from phase: :fetch in step Burrito.Steps.Fetch.ResolveERTS
** (exit) 1
    (burrito 0.8.0) lib/builder/builder.ex:155: anonymous fn/3 in Burrito.Builder.run_phase/2
    (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.16.0) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.8.0) lib/builder/builder.ex:95: Burrito.Builder.build/1
    (mix 1.16.0) lib/mix/tasks/release.ex:1076: Mix.Tasks.Release.run_steps/1
    (mix 1.16.0) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.16.0) lib/mix/cli.ex:96: Mix.CLI.run_task/2
    /Users/matt/.asdf/installs/elixir/1.16.0-otp-26/bin/mix:2: (file)

In fact I actually do have 7zip installed via homebrew:

➜  rez git:(main) ✗ brew install 7zip
Warning: sevenzip 23.01 is already installed and up-to-date.

However it seems to have installed the command as "7zz" rather than "7z".

In the example above, BUILD_MODE is how I select between code for escript and code for Burrito (e.g. how command line arguments are obtained).

**Comment by binaryape** [comment]
I'm getting something similar - I'm trying Burrito for the first time today and get this:

```
--> Resolving ERTS: {:precompiled, [version: "25.3.2.8"]}
--> Remote ERTS From Beam Machine: https://beam-machine-universal.b-cdn.net/OTP-25.3.2.8/macos/universal/otp_25.3.2.8_macos_universal_ssl_3.1.4.tar.gz?please-respect-my-bandwidth-costs=thank-you
--> Downloading file: https://beam-machine-universal.b-cdn.net/OTP-25.3.2.8/macos/universal/otp_25.3.2.8_macos_universal_ssl_3.1.4.tar.gz?please-respect-my-bandwidth-costs=thank-you
** (RuntimeError) Failed to fetch https://beam-machine-universal.b-cdn.net/OTP-25.3.2.8/macos/universal/otp_25.3.2.8_macos_universal_ssl_3.1.4.tar.gz?please-respect-my-bandwidth-costs=thank-you! (Got 404) Perhaps we haven't built a pre-compiled Erlang for this release yet? If this was a 404, please file an issue! Thanks!
    (burrito 1.0.2) lib/util/default_erts_resolver.ex:95: Burrito.Util.DefaultERTSResolver.do_download/2
```

Is there a way to see which precompiled Erlang versions are available?

**Comment by doawoo** [comment]
@binaryape hey there! It looks like I either missed this exact version of OTP or there was an issue that prevented me from supporting it on all platforms -- you can get a list of all the versions here: https://beammachine.cloud

I'm out of state rn so I can't check or kick off a build for your exact version -- I'll follow up on that later!

**Comment by doawoo** [comment]
@mmower hey I'll take a look at this when I get back home :)

**Comment by doawoo** [comment]
@binaryape I just built and uploaded that OTP version, I missed it apparently! Your build should work now!

@mmower I recommend you update to the new official Hex.pm release of Burrito, I see you're running 0.8.0 which is super old -- it should be version 1.0.x 🙂 

For your 7zip issue, install the `p7zip` package using brew and not the "sevenzip" package

**Comment by mmower** [comment]
Sorry if this re-opens the issue but I wanted to say "Thank you" @doawoo. I hadn't realised there was now an official release of Burrito. Just managed to build all 3 targets successfully :)

**Comment by binaryape** [comment]
Now it's reopened I'll add my thanks too :-)
