### ISSUE TITLE
Consider scoping environment variables to the specific packaged app

### ISSUE THREAD

**Issue by QuinnWilton** [burrito-elixir/burrito#13]
Right now Burrito relies on hardcoded environment variables like `APPLICATION_INSTALL_DIR`. There's nothing tying these names to the specific app in question, and we probably don't want to leak Burrito as an implementation detail, so we may want want to investigate using environment variables that are based on the name of the application in question, like: `MY_APP_INSTALL_DIR` 

Burrito already has access to the OTP app name, so we could leverage that easily. This would also allow Burrito applications to be configured independently of each other.

**Comment by ashea-code** [comment]
this is all set in the latest release!
