### ISSUE TITLE
the module attributes is enclosed during compile time.

### ISSUE THREAD

**Issue by madper** [burrito-elixir/burrito#132]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**:  MacOS
**Host CPU**: aarch64

Please run `zig version` in your Burrito project directory and write the version here:
0.11.0

Please run `elixir -v` in your Burrito project directory and write the version here:
```
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.16.1 (compiled with Erlang/OTP 26)
```
------

### Target

**Host OS**: Linux
**Host CPU**: both x86_64 and aarch64 
**Host LibC and Version**: I generated a complete static file.

------

```
defmodule Rpc do
@hostname :inet.gethostname() |> elem(1) |> to_string

def validate(topic) do
   getHostname(topic) = @hostname
end

end
```

The `@hostname` will alwalys store the hostname of the machine which I compile the binary. It won't be the hostname that run the binary.

**Comment by doawoo** [comment]
This isn't a bug or anything related to burrito. It's actually a feature of Elixir! 😃 
Module attributes are resolved at compile time, not at runtime. So the expression given is evaluated at compile time. 

Take a look at the official Elixir docs: https://hexdocs.pm/elixir/module-attributes.html
Specifically the section "As Constants" where it gives an example of how a function called in an attribute will be eval'd at compile time only.

**Comment by madper** [comment]
Oooh I see. Without burrito I simple share the source code directly and compile it locally.
Thanks tons for the comment!
