### ISSUE TITLE
Cache Erlang (OTP) to local instead of re-downloading everytime

### ISSUE THREAD

**Issue by xhh** [burrito-elixir/burrito#14]
Everytime I run `MIX_ENV=prod mix release`, it downloads OTP from github (for win64):

```shell
16:07:33.233 [info]  Downloading replacement ERTS: https://github.com/erlang/otp/releases/download/OTP-24.0.6/otp_win64_24.0.6.exe
```

which takes much time (in my location). Would it be better to cache it somewhere?

**Comment by QuinnWilton** [comment]
This is an excellent suggestion and is something that we should support. We have a story tracked internally for this, but haven't prioritized it yet because it hasn't been enough of an issue from our location. I'll chat with @ashea-code in the morning about it.

Thank you!

**Comment by ashea-code** [comment]
Hey there! +1 on this, I'm also keen on adding an option that allows the ERTS location to be passed in as a local path, so if you have a custom build you'd rather source, we can use that as well.

**Comment by ashea-code** [comment]
Hey there! we just merged in a local ERTS cache which should solve this for you!
If you run into any more issues feel free to re-open the issue/create a new one.

**Comment by xhh** [comment]
Just retried the last code and confirmed that the cache works great.
