### ISSUE TITLE
Get the folder of the original wrapped executable from within the application

### ISSUE THREAD

**Issue by Filechaser** [burrito-elixir/burrito#143]
Burrito seems to unpack its content to another folder. The Environment Variables just seem to have the path to the extracted payload. ETS file

Unfortunately I couldnt get the original path to the executable the user clicks on when starting my packed application.
The user can move this single executable wherever he likes and i should be able to know where it is located.
With environment variables i only get the location of the extracted file
It is not in the environment variable and not passed as an argument. Could someone help me with that problem.

I wish to know the original executable's location to access Settings.yml files stored alongside it.
 File.cwd does unfortunately only return the users home directory on mac osx. On Windows File.cwd would work
 
 Can we introduce a Environment variable that always has the wrapped burrito executable's location?

**Comment by Filechaser** [comment]
Sorry, I posted the question to the wrong GitHub project.
Case Closed

**Comment by harrisi** [comment]
I think this is the most relevant issue for me, but I'm not sure if it's related to my problems. Let me know if I should open a new issue.

My situation is that I use `priv/` as a folder for relevant assets to my project. When building locally, I can reference `priv/foo/bar.mp3`, for example, but the build doesn't seem to include it. I'm not sure if it's included and I just need to reference the path differently or if I need to set some values to package the `priv` directory or something.

Any help would be great! The repo is https://github.com/harrisi/elixir_breakout, if that helps.

**Comment by doawoo** [comment]
@harrisi I think your issue might be unrelated, but I might know what's going on, make sure you use this method of computing your priv directory:

```elixir
priv_dir = :code.priv_dir(:breakout)
```

That we you get an absolute path to `priv` and not a relative one. See if that helps.

In addition, I'll be adding an env var to get the original executable path in the wrapper.

**Comment by doawoo** [comment]
I've merged in a new utility function `Burrito.Util.Args.get_bin_path/0` which will allow you to fetch the original binary path. I'll close this issue for now! 
It will roll out in the next Hex release :)
