### ISSUE TITLE
Unable to run in Windows 11 - 

### ISSUE THREAD

**Issue by gazzer82** [burrito-elixir/burrito#148]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: MacOS 14.2.1 (23C71)
**Host CPU**: arm64 (Apple M1 Max)

Please run `zig version` in your Burrito project directory and write the version here: 0.13.0

Please run `elixir -v` in your Burrito project directory and write the version here: Elixir 1.16.2 (compiled with Erlang/OTP 26)

------

### Target

**Host OS**: Windows 11
**Host CPU**: x86_64
**Host LibC and Version** (eg. gnu/musl x.y.z ...)

------

I have cross compiled a Phoenix application to Windows/Linux and Mac targets. The Linux and Mac targets work as expected, but when running the Windows version the application halts with the following error:

```
Unable to load emulator DLL
(C:\Users\*\AppData\Local\.burrito\*_*_erts-14.2.2_2.3.0\erts-14.2.2\bin\beam.smp.dll)
```

Not being an OTP/Windows expert, I'm not entirely sure what the error is telling me, I can confirm that the .dll file is in that location, but i'm guessing that's not the issue.

I am using the pre-compiled ERTS builds currently.

**Comment by doawoo** [comment]
Hmm, running the example CLI app built on my MacOS M1 machine results in a runnable binary for me... can you post any more of the logs when trying to run this exe?

**Comment by doawoo** [comment]
I'm closing this issue to keep things tidy in the project page. If you are still experiencing this error, provide more log output, or try the `example_cli` project in the repo.
