### ISSUE TITLE
Very quick question

### ISSUE THREAD

**Issue by nhpip** [burrito-elixir/burrito#149]
Hi,

So I have an elixir app, but for reasons beyond my control I've been asked if the app can be deployed in a linux distro without a shell (bash, sh etc).

Calling: `./burrito_out/my_app_linux` directly.

Does Burrito assume a shell exists?

Thanks

**Comment by doawoo** [comment]
The only things Burrito needs for linux are the following:

* tempfs mounted at `/tmp` to extract its static musl runtime (only needed if you use our pre-compiled ERTS)
* write access _somewhere_ to deploy the app payload, you can override where this extraction takes place with an environment variable, which is computed based on the name of your app: https://github.com/burrito-elixir/burrito/blob/efd6a329f26e4039e7d46d00e571dc1df5b69262/src/wrapper.zig#L161

(In the case of the `:example_cli_app` app the env variable would be `EXAMPLE_CLI_APP_INSTALL_DIR=...`

Overall I think this is entirely doable, if you were to set up your linux system properly and have the burrito app be the first app that runs, everything should work as expected.

**Comment by nhpip** [comment]
Many thanks
