### ISSUE TITLE
Missing ERTS 25.3.2.15

### ISSUE THREAD

**Issue by dergraf** [burrito-elixir/burrito#160]
### Host & Target

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: RedHat using Nix
**Host CPU**: x86_64

Please run `zig version` in your Burrito project directory and write the version here:
0.13.0

Please run `elixir -v` in your Burrito project directory and write the version here:

Elixir 1.17.3 (from current Nix unstable)

Missing ERTS.

Is it possible that you upload the missing ERTS or should we take the path of custom ERTS?

Thanks and best regards
Andre

**Comment by doawoo** [comment]
Built and uploaded! Your builds should work now, sorry for the delay.

**Comment by dergraf** [comment]
Thank you very much for the prompt reaction! 

Btw,we found a workaround where we could generate a TarGz from the ERTS that is currently running the mix task using `:code.root_dir()` . I am aware that this isn't a cross-platform solution but I guess may work as a sound workaround in cases a pre bundled ERTS doesn't exist on your end. Do you see any points against using an ERTS generated from the current `:code.root_dir()` ?

**Comment by doawoo** [comment]
Using the generated ERTS from `:code.root_dir()` certainly isn't portable, but if that enables you to build pre-releases for testing I don't see anything wrong with that.

The ability to provide a custom ERTS is designed to free you from our provided erlangs whenever you wish :)
