### ISSUE TITLE
example_cli_app failed right at the first run on Windows 10

### ISSUE THREAD

**Issue by tduccuong** [burrito-elixir/burrito#163]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: Debian 12 
**Host CPU**: x86_64

Please run `zig version` in your Burrito project directory and write the version here: 
0.13.0

Please run `elixir -v` in your Burrito project directory and write the version here:
1.15.5

------

### Target

**Host OS**: Windows 10 Build 19045
**Host CPU**: x86_64
**Host LibC and Version** : Sorry, not sure how to check that in Windows!

------

After successfully done `MIX_ENV=prod mix release`, I copy the `example_cli_app_windows.exe` to the Windows 10 machine, open PowerShell and do:
```
.\example_cli_app_windows.exe
```

I got this error immediately:
```
Program 'example_cli_app_windows.exe' failed to run: Access is deniedAt line:1 char:1
+ .\example_cli_app_windows.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\example_cli_app_windows.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

Then the file `example_cli_app_windows.exe` just disappeared. It seemed it was deleted!!

In the README of the Burrito homepage, looking at the requirements for Windows, it says:

```
Windows
- MSVC Runtime for the Erlang version you are shipping
- Windows 10 Build 1511 or later (for ANSI color support)
```

I think the 2nd point is guaranteed as my target Windows build is greater than 1511. The 1st point, however, I don't know how to achieve it. Could anyone please elaborate on it?

As I moved on from Bakeware and found Burrito, I am really expecting this to work. 

Thanks a lot for any help!

**Comment by doawoo** [comment]
I cannot reproduce this: 

![image](https://github.com/user-attachments/assets/40294bb8-a04c-4625-8f1d-c7af4272ddad)

> Then the file example_cli_app_windows.exe just disappeared. It seemed it was deleted!!

This sounds like either Windows or some other anti-virus software deleted the file because it mistook it for something malicious.

You can ensure you have the MSVC runtime installed by using my handy site: [https://](https://vcredist.wtf) - Install the 2019, 2017, 2015 version for your architecture.

**Comment by tduccuong** [comment]
Thanks for your quick response. I installed MSVC from your site. But still got the same error i.e., `Access is denied At line: 1 char:1 ...`. The target machine has Crowdstrike Falcon Sensor installed. So it could be because of that? Unfortunately, I am not allowed to turn that off.

So beside that error, another question: Is MSVC a hard requirement? Because my user will have absolutely no idea what that is, how to install and why do they have to install that!

Thanks a lot.

**Comment by doawoo** [comment]
> The target machine has Crowdstrike Falcon Sensor installed. So it could be because of that? Unfortunately, I am not allowed to turn that off.

That's exactly why it's not working. Crowd Strike dislikes burrito. When I was first developing it, I ran into this issue and had to request that my IT department add an exception for the program and the directory where it extracts the files to.

> So beside that error, another question: Is MSVC a hard requirement? Because my user will have absolutely no idea what that is, how to install and why do they have to install that!

MSVC is a hard  MSVC, however it's required for Erlang to run at all, so it's not a Burrito requirement, it's an Erlang requirement. Without it Bakeware wouldn't run either, or any Erlang install. The good news is most new Windows 10/11 installs will already have this installed.

**Comment by tduccuong** [comment]
so, to avoid crowdstrike, I installed a fresh Windows 10 Home Edition in a Virtualbox VM. The app now seems to run, but nothing appears, so I am not sure now...

```
PS C:\Users\CT\Downloads> dir


    Directory: C:\Users\CT\Downloads


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        12/16/2024   6:48 PM       18354176 example_cli_app_windows.exe


PS C:\Users\CT\Downloads> .\example_cli_app_windows.exe
PS C:\Users\CT\Downloads>
```

That is the output, after pressing Enter, it hangs around 30 seconds then returns without any output like that. Can you please advice further?

Thanks a lot!

**Comment by doawoo** [comment]
Ah yes eventually Windows updates will install the redistributable, or any other modern application. It's required by many. 

The only way around CrowdStrike is you have your IT department whitelist the application. I cannot do anything to mitigate it, CrowdStrike is aggressive and usually has tons of false positives. I suggest talking to whoever manages your system deployments.
