### ISSUE TITLE
Results  from attempted run on Apple M1

### ISSUE THREAD

**Issue by lawik** [burrito-elixir/burrito#2]
Vanilla:

```
lawik@m1mini example % arch                                      arm64
lawik@m1mini example % mix release                               Release example_cli_app-0.1.0 already exists. Overwrite? [Yn] y
* assembling example_cli_app-0.1.0 on MIX_ENV=dev
* skipping runtime configuration (config/runtime.exs not found)

17:19:16.758 [info]  Burrito build target is: :native

17:19:17.255 [info]  Build working dir: /var/folders/fj/m1gn99tx05v1h8tdwtkkhgvr0000gn/T/burrito_build_36CCA0C1B4461889

17:19:17.256 [info]  Patching shell script for release...

17:19:17.259 [info]  Generating wrapper metadata file...

17:19:17.481 [error] Burrito failed to wrap up your app! Check the logs for more information.
** (exit) 1
    (burrito 0.4.0) lib/burrito.ex:219: Burrito.do_wrap/5
    (elixir 1.12.3) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.4.0) lib/burrito.ex:34: Burrito.wrap/1
    (mix 1.12.3) lib/mix/tasks/release.ex:1047: Mix.Tasks.Release.run_steps/1
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
```

With rosetta?

```
lawik@m1mini example % arch -x86_64 mix release                  Release example_cli_app-0.1.0 already exists. Overwrite? [Yn] y
* assembling example_cli_app-0.1.0 on MIX_ENV=dev
* skipping runtime configuration (config/runtime.exs not found)

17:22:30.892 [info]  Burrito build target is: :native

17:22:31.382 [info]  Build working dir: /var/folders/fj/m1gn99tx05v1h8tdwtkkhgvr0000gn/T/burrito_build_9566FAB46C2CEF47

17:22:31.383 [info]  Patching shell script for release...

17:22:31.393 [info]  Generating wrapper metadata file...

17:22:32.119 [error] Burrito failed to wrap up your app! Check the logs for more information.
** (exit) 1
    (burrito 0.4.0) lib/burrito.ex:219: Burrito.do_wrap/5
    (elixir 1.12.3) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.4.0) lib/burrito.ex:34: Burrito.wrap/1
    (mix 1.12.3) lib/mix/tasks/release.ex:1047: Mix.Tasks.Release.run_steps/1
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

Hope that is useful, let me know if I should try anything else :)

**Comment by ashea-code** [comment]
Quick bump on this I have acquired a new Macbook with an M1, so I'll have a better time testing this stuff!
Additionally I believe I have the flags to compile apple silicon erlang in our erlang-builder repo -- hopefully I can get that up soon!

**Comment by sax** [comment]
I was just curious about the state of this. I'd like to try out burrito to wrap up a CLI tool I wrote using Ratatouille, but it would need to run on (at least) M1 and Intel Macs.

I'm happy to contribute to fixes (within my abilities), but thought I'd ask if there was any known issue or workaround first.

**Comment by doawoo** [comment]
@sax hello!

Since we just refactored the build pipeline that should be fairly doable now. I don't think we offer a ton of pre-built ERTS release for aarch64 Darwin but that's something I want to resolve sooner rather than later... 

But I think the following process could get you what you want:

1. Ensure you're using the latest release of Burrito from the `main` branch
2. Unlock our dependency on Zig 0.9.0 (which is there for stability, but their nightly builds have fixed a Mach-O linker issue for cross-compiling NIFs)
3. Build a custom ERTS for Intel or aarch64 (whichever your build machine _isn't_) the README has a section on this!
3. Configure your Burrito targets so they look something like this:

```
...
  # If you are building on an Intel machine, provide an ERTS compiled for aarch64 like below
  # flop this around if you are building on aarch64 targeting Intel 
  targets: [
    macos: [os: :darwin, cpu: :x86_64],
    macos_m1: [os: :darwin, cpu: :aarch64, local_erts: "/path/to/darwin_aarch64_erts.tar.gz"],
  ]
...
```

I haven't tested this, but in theory it should get you the ability to produce M1 and Intel compatible binaries

**Comment by sax** [comment]
Awesome, thank you! I haven't yet tried the cross-compile, but after a few tries I got an M1 build working.

One suggestion: I had to do a few iterations before I found all the things I needed to do. Maybe it would be helpful to add the following to the README?
* Brew packages
* asdf zig plugin
* Overriding zig version in deps/burrito

I could do a pull request for those. I'm going to try cross-compiling to x86_64 first, though.

**Comment by sax** [comment]
Oh... another thought is that if zig is already in the path (ie, from an application's `.tool-versions`), to use that instead of the version specified in deps. Maybe print out a warning when this happens, so it's less surprising if tragedy ensues?

**Comment by krns** [comment]
Just tested to build for aarch64 on my M1 Pro and had no problems :-)
