### ISSUE TITLE
Burrito CLI

### ISSUE THREAD

**Issue by wojtekmach** [burrito-elixir/burrito#32]
When wrapping Elixir code with Burrito we need a few things: a Mix project with Burrito dep and a proper build environment (Zig, 7z, etc) which adds a little bit of friction.

Let's say we have this very simple Elixir script:

```
$ cat echo.exs
IO.puts Enum.join(System.argv(), " ")
$ elixir echo.exs foo bar
foo bar
```

To remove the friction, we could have a `burrito` CLI that allows us to build the binary off of a script like this:

```
$ burrito echo.exs
$ ./echo foo bar
foo bar
$ file echo
echo: Mach-O 64-bit executable arm64
```

we could easily cross-compile it too:

```
$ burrito echo.exs -target x86_64-windows
$ file echo
echo: PE32+ executable (console) x86-64, for MS Windows
```

The `burrito` executable would contain everything it needs to build binaries, Burrito itself, Zig, 7z, etc. It would also properly handle system args (e.g. via `System.argv(Burrito.Util.Args.get_arguments())` before executing the script) and ideally `Mix.install` too.

Now, we would need to have the CLI as executable per supported target. The best part is we'd ideally be able to wrap burrito CLI with burrito itself. :)

**Comment by ashea-code** [comment]
This is a fantastic idea! A burrito wrapped burrito sounds mind-bending but also perfect for this.
I hope to look into this soon

**Comment by andyl** [comment]
Here's a comparable in the js/deno world: [deno compile](https://deno.land/manual@v1.32.5/tools/compiler)

**Comment by doawoo** [comment]
I'm still considering this, but, I'm going to close this for now to tidy up the issue list.

**Comment by rupurt** [comment]
This is what I've come up with so far to handle

- `mix test`
- `mix run`
- `iex`
- `./my-app`

```elixir
defmodule Bos do
  @moduledoc """
  TODO...
  """

  use Application

  def start(_type, _args) do
    init_argv = Burrito.Util.Args.get_arguments()
    IO.puts("-------- INIT ARGV: #{inspect(init_argv)}")
    run_cli(init_argv)
    {:ok, self()}
  end

  defp run_cli([arg0 | rest] = argv) do
    cond do
      Path.basename(arg0) == "mix" -> mix_run_cli(rest)
      ["--no-halt", "+iex" | _] = argv -> :ok
      true -> Bos.CLI.run(argv)
    end
  end

  defp run_cli(argv) do
    Bos.CLI.run(argv)
  end

  defp mix_run_cli([]) do
    Bos.CLI.run([])
  end

  defp mix_run_cli(["run" | rest]) do
    case rest do
      ["--no-halt" | no_halt_rest] -> mix_run_cli(no_halt_rest)
      _ -> Bos.CLI.run(rest)
    end
  end

  defp mix_run_cli(["test" | _rest]) do
    :ok
  end
end
```
