### ISSUE TITLE
Building a windows release with the hexpm/elixir docker image missing `elixir.bat`

### ISSUE THREAD

**Issue by bsedat** [burrito-elixir/burrito#42]
If a mix release is compiled with a docker image such as hexpm/elixir:1.13.1-erlang-24.1.7-alpine-3.14.2 it seems to be missing the expected `releases\<VERSION>\elixir.bat` file. 
In the mix release output I see this output: "skipping elixir.bat for windows (bin/elixir.bat not found in the Elixir installation)"

I suspect that the hexpm images may not have the windows-specific .bat files present (I think mix release is searching for it in `"/usr/local/lib/elixir/bin"`). Perhaps burrito should substitute it in?

**Comment by bsedat** [comment]
Same result with the official Elixir image, which is also missing that file in the bin directory. ASDF-installed Elixir seems to be alright though, so I'm exploring that as a workaround.

**Comment by doawoo** [comment]
Thanks Ben!
I think it's a reasonable thing to vendor out our own `elixir.bat` file based on how infrequently it changes. We already produce our own startup scripts anyways.

**Comment by josevalim** [comment]
Please open up an issue (or send a PR) to https://github.com/hexpm/bob. We should include the windows files IMO, exactly for cross-compilation purposes. :)

**Comment by doawoo** [comment]
This is fixed now that we launch directly from zig!
