### ISSUE TITLE
Bundle multiple libc ERTS runtimes in a single binary

### ISSUE THREAD

**Issue by bsedat** [burrito-elixir/burrito#48]
After some ERTS libc architecture mixups (entirely my user error) I wanted to propose an enhancement to bundle multiple ERTS runtimes and at runtime decide which version to extract based on detecting the user's libc environment.

Another issue I ran into (not Burrito's fault either) but running the wrong ERTS gives an error message like:
```
/tmp/.tinfoil/XXXX_erts-12.1.5_XXXX/releases/XXXX/../../erts-12.1.5/bin/erl: 10: exec: /tmp/.tinfoil/XXXX_erts-12.1.5_XXXX/erts-12.1.5/bin/erlexec: not found
```
which is really complaining that `erlexec` could not find the libc .so file.

**Comment by doawoo** [comment]
Progress has been made on this recently. Newer BEAM Machine built VMs will ship with totally static musl libc, openssl etc.
