### ISSUE TITLE
 Failed to rebuild exqlite for x86_64-windows-gnu (using Mac as build machine)

### ISSUE THREAD

**Issue by mazz-seven** [burrito-elixir/burrito#6]
Hey, 
First, I want to thank you for your great work and contribution to the elixir community. 

I'm trying to build this desktop example project https://github.com/elixir-desktop/desktop-example-app for windows and mac. The project is using exqlite. 

For macOS, everything works flawlessly, but for windows, I get this error. 
```
15:03:49.313 [info]  Replaced NIF with DLL /var/folders/df/hnx1cxn13b7gxdyvf352_tsr0000gp/T/erts-B4DB6B3615770557/lib/crypto-5.0.4/priv/lib/crypto_callback.dll

15:03:49.316 [info]  Replaced NIF with DLL /var/folders/df/hnx1cxn13b7gxdyvf352_tsr0000gp/T/erts-B4DB6B3615770557/lib/crypto-5.0.4/priv/lib/otp_test_engine.dll

15:03:49.316 [warn]  We couldn't find a replacement for NIF /var/folders/df/hnx1cxn13b7gxdyvf352_tsr0000gp/T/burrito_build_1EB669BE39668493/lib/exqlite-0.7.9/priv/sqlite3_nif.so, the binary may not work!

15:03:49.317 [info]  Replaced NIF with DLL /var/folders/df/hnx1cxn13b7gxdyvf352_tsr0000gp/T/erts-B4DB6B3615770557/lib/wx-2.1/priv/erl_gl.dll

15:03:49.327 [info]  Replaced NIF with DLL /var/folders/df/hnx1cxn13b7gxdyvf352_tsr0000gp/T/erts-B4DB6B3615770557/lib/wx-2.1/priv/wxe_driver.dll

15:03:49.328 [info]  Deleting .pdb files, we don't need them...

15:03:49.366 [info]  Patching shell script for release...

15:03:49.871 [info]  Going to recompile NIF for cross-build: exqlite -> x86_64-windows-gnu
rm -f /priv/sqlite3_nif.so /priv/sqlite3_nif.a /obj/sqlite3.o /obj/sqlite3_nif.o
mkdir -p /priv
mkdir: /priv: Read-only file system
make: *** [/priv] Error 1

15:03:49.900 [error] Failed to rebuild exqlite for x86_64-windows-gnu!

15:03:49.900 [error] [__struct__: IO.Stream, device: :standard_io, line_or_bytes: :line, raw: false]
** (exit) 1
    (burrito 0.5.0) lib/burrito.ex:281: Burrito.maybe_recompile_nif/4
    (elixir 1.12.2) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.5.0) lib/burrito.ex:144: Burrito.do_wrap/5
    (elixir 1.12.2) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.5.0) lib/burrito.ex:37: Burrito.wrap/1
    (mix 1.12.2) lib/mix/tasks/release.ex:1047: Mix.Tasks.Release.run_steps/1
    (mix 1.12.2) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.2) lib/mix/cli.ex:84: Mix.CLI.run_task/2
    (elixir 1.12.2) lib/code.ex:1261: Code.require_file/2
```

From what I saw in [exqlite](https://github.com/elixir-sqlite/exqlite) repo, they have a makefile for windows and they are using elixir_make. But I cannot understand why the rebuild is failling. 

Appreciate your help. 
Z.

**Comment by ashea-code** [comment]
Hi! Thanks for the report, this is an very interesting issue. What is the working directory of the mix project you're in? 
Additionally, would it be possible for you to provide a minimal example of the project so I can test this myself? (If it's just a simple project with exqlite installed that's fine, and I can try that)

**Comment by mazz-seven** [comment]
Hey, thanks for replying. 
You can try https://github.com/elixir-desktop/desktop-example-app example project. It's what I tried to compile. 
If you need a simplified version I can do it tomorrow :)

**Comment by ashea-code** [comment]
Just bumping this to let you know we haven't forgotten about it, now that the new build pipeline is in place and we are past holidays we hope to start tackling the issue backlog

**Comment by doawoo** [comment]
Cleaning up the issues tab a bit today.

We've made a ton of updates to the build pipeline. And things may be fixed for you!

If you are still having issues please feel free to re-open/re-create this issue :)
