### ISSUE TITLE
warning: Burrito.wrap/1 is undefined

### ISSUE THREAD

**Issue by bsedat** [burrito-elixir/burrito#64]
When ElixirLS is building a project with Burrito releases it warns `warning: Burrito.wrap/1 is undefined (module Burrito is not available or is yet to be defined)` - this is somewhat expected because it is evaluating `mix.exs` and Burrito isn't available yet.

I was hoping to solve this with an `xref exclude` in the mix project configuration but that didn't seem to do it. Not a high priority at all but figured I would ask so we can combine minds and see if there is an easy solution.

**Comment by doawoo** [comment]
Going to close this to clean up issues for now -- but I'm still interested in squashing this minor annoyance.
