### ISSUE TITLE
Windows ETRS v13 failed to load NIF public_key

### ISSUE THREAD

**Issue by tim-smart** [burrito-elixir/burrito#66]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: MacOS 12.4
**Host CPU**: x86_64

Please run `zig version` in your Burrito project directory and write the version here: 0.9.1

Please run `elixir -v` in your Burrito project directory and write the version here: 1.13.4

------

### Target

**Host OS**: Windows 11
**Host CPU**: x86_64

------

Running the .exe issues the following error:

```
"Failed to load NIF library c:/Users/ariseit/AppData/Local/.burrito/burrito_erts-13.0_0.1.0/lib/public_key-1.13/priv/lib/public_key: 'The specified module could not be found.'"
```

**Comment by tim-smart** [comment]
Downgrading to ERTS 12 is a workaround.

**Comment by doawoo** [comment]
Hey there! I’ll take a look at this as soon as I can.

**Comment by doawoo** [comment]
I've been able to re-produce this locally on my M1 machine compiling for Windows 10/11 -- I'm starting an investigation now...

**Comment by doawoo** [comment]
Just opened a PR to help address this!

https://github.com/burrito-elixir/burrito/pull/67

**Comment by doawoo** [comment]
Merged!

**Comment by tim-smart** [comment]
🔥
