### ISSUE TITLE
Trying to get Burrito working with sqlite on linux -> windows

### ISSUE THREAD

**Issue by adamzaninovich** [burrito-elixir/burrito#69]
We use Burrito to build our phoenix app as a windows exe inside of a ubuntu linux github action CI pipeline.

We recently added sqlite to our app, and we're having trouble with the cross compile since it's not included in the precompiled dlls.

```
---> We couldn't find a replacement for NIF
	/tmp/burrito_build_847977B189F27DE3/lib/exqlite-0.11.6/priv/sqlite3_nif.so
	The binary may not work!
```
and later, while trying to cross compile the nif...
```
c_src/sqlite3_nif.c:10:10: fatal error: 'erl_nif.h' file not found
Warning: #include <erl_nif.h>
         ^~~~~~~~~~~
1 error generated.
make: *** [Makefile:132: obj/sqlite3_nif.o] Error 1
---> Failed to rebuild exqlite for x86_64-windows!
```

I'm a little unsure on how to proceed from here, and I'm hoping that someone might have some previous experience or insight that might help.

**Comment by adamzaninovich** [comment]
I'm also seeing this, which seems related:
```
ignoring nonexistent directory "-I/tmp/unpacked_erts_AA0DF667AD2C0513/otp-windows/erts-12.1.1/include"
ignoring nonexistent directory "-fPIC"
ignoring nonexistent directory "/home/adam/.asdf/installs/zig/0.9.1/lib/libc/include/x86_64-windows-gnu"
ignoring nonexistent directory "/home/adam/.asdf/installs/zig/0.9.1/lib/libc/include/generic-mingw"
ignoring nonexistent directory "/home/adam/.asdf/installs/zig/0.9.1/lib/libc/include/x86_64-windows-any"
#include "..." search starts here:
#include <...> search starts here:
 c_src
 /home/adam/.asdf/installs/zig/0.9.1/lib/include
 /home/adam/.asdf/installs/zig/0.9.1/lib/libc/include/any-windows-any
End of search list.
c_src/sqlite3_nif.c:10:10: fatal error: 'erl_nif.h' file not found
```

**Comment by adamzaninovich** [comment]
Update: `erl_nif.h` IS included in the otp-windows/erts that burrito downloads! But it's not looking in the directory because there's an extra `-I` in the pathname that is preventing it.

**Comment by doawoo** [comment]
Hey Adam! Sorry for a late reply, it's been a busy week.
I'll try and look into this issue shortly, thanks for filing the issue and for all the investigative work you've done so far! I figured there was something funky going on with the include paths.

**Comment by doawoo** [comment]
Update: I've uncovered a few more bugs with the `elixir_make` override system we're using, I'm working on a fix for your issue, and also a small refactor that would improve NIF recompilation in general (for `elixir_make` targets)

**Comment by doawoo** [comment]
I believe https://github.com/burrito-elixir/burrito/pull/70 fixes this issue, I was able to include `exsqlite` in an example project, recompile it for windows, and run the binary on a Windows VM

**Comment by doawoo** [comment]
@adamzaninovich mind giving the latest `main` branch a try? NOTE that you'll need to update to zig 0.10.0 on your local machine

**Comment by adamzaninovich** [comment]
@doawoo sorry work has been crazy the last few weeks, but I'm planning to get back to this this week. I will let you know how it goes with the `main` branch and zig 0.10. Thanks for looking into it!

**Comment by doawoo** [comment]
Hey there! I'm cleaning up the issues tab a bit.
If things are fixed for you, great! If you still have some issues feel free to re-open it :)

**Comment by adamzaninovich** [comment]
@doawoo apologies for not getting back to you. It's working great now. Thanks for the fix!
