### ISSUE TITLE
phoenix app fails to run after packaging with missing RELEASE_SYS_CONFIG error

### ISSUE THREAD

**Issue by photomattmills** [burrito-elixir/burrito#82]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: MacOS 13.2.1
**Host CPU**: arm64

Please run `zig version` in your Burrito project directory and write the version here:
`0.10.1`

Please run `elixir -v` in your Burrito project directory and write the version here:
```
Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 25)
```
------

### Target
Same as above

------

In a brand new phoenix app, just `mix phx.new` and add burrito configs copied from the example mix.exs, when starting the packaged app, it dies with the following erlang error: 
```
{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.ArgumentError',message=><<"could not fetch environment variable \"RELEASE_SYS_CONFIG\" because it is not set">>},[{'Elixir.System','fetch_env!',1,[{file,"lib/system.ex"},{line,698}]},{'Elixir.Config.Provider','resolve_config_path!',1,[{file,"lib/config/provider.ex"},{line,185}]},{'Elixir.Config.Provider',boot,1,[{file,"lib/config/provider.ex"},{line,222}]},{init,eval_script,2,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({,[{Elixir.System,fetch_env!,1,[{_},{_}]},{Elixir.Config.Provider,resolve_config_path!,1,[{_},{_}]},{Elixir.Config.Provider,boot,1,[{_},{_}]},{init,eval_script,2,[]},{init,do_boot,3,[]}]})
```
It looks like it's trying to load a custom config provider with "RELEASE_SYS_CONFIG" in the config tuple, but it's not there. There's no custom config provider in the app, and that string isn't anywhere in our whole dependency tree. I first encountered this in a non-trivial app, this is just a repro case. It started happening after we upgraded to the latest version `425613d`.

**Comment by photomattmills** [comment]
Also of note, the example app from this repo works fine on the same system.

**Comment by doawoo** [comment]
Hi there! I have located the issue, we aren't setting a few environment variables that the default Config provider requires when using a `runtime.exs` file, which the example app does not!

Working on a fix now.

**Comment by doawoo** [comment]
@photomattmills go ahead and pull the latest `main` branch and see if that fixes things! Also I just realized that in order for phx app to run you need to export `PHX_SERVER=true` before running the wrapped application.

Perhaps we can provide a way to set env variables in the wrapped app via mix.exs or something similar.

**Comment by photomattmills** [comment]
Dude! thanks for getting to this so quickly. It's working now.

**Comment by adamzaninovich** [comment]
@doawoo thanks for the save!

**Comment by photomattmills** [comment]
@doawoo Just realized that it's still broken in the same way on windows. We tried to modify the same file to pass the environment vars to the windows process too, but it didn't work, and I don't know zig or windows processes well enough to know if we're on the right track. 
```zig
if (builtin.os.tag == .windows) {
        // Fix up Windows 10+ consoles having ANSI escape support, but only if we set some flags
        win_asni.enable_virtual_term();
        const final_args = try std.mem.concat(allocator, []const u8, &.{ erlang_cli, args_trimmed });

        var win_child_proc = std.ChildProcess.init(final_args, allocator);

        var erl_env_map = EnvMap.init(allocator);
        defer erl_env_map.deinit();

        var env_map_it = env_map.iterator();
        while (env_map_it.next()) |entry| {
            const key = entry.key_ptr.*;
            const val = entry.value_ptr.*;
            try erl_env_map.put(key, val);
        }

        try erl_env_map.put("RELEASE_ROOT", install_dir);
        try erl_env_map.put("RELEASE_SYS_CONFIG", config_sys_path_no_ext);
        
        win_child_proc.env_map = erl_env_map;
        win_child_proc.stdout_behavior = .Inherit;
        win_child_proc.stdin_behavior = .Inherit;

        log.debug("CLI List: {s}", .{final_args});

        const win_term = try win_child_proc.spawnAndWait();
        switch (win_term) {
            .Exited => |code| {
                std.process.exit(code);
            },
            else => std.process.exit(1),
        }
    } else {
```

**Comment by doawoo** [comment]
OH I forgot about the windows special case.. I'll have to get a VM up for this. That _looks_ correct to me, but there's always something odd in Windows processes since we can't just `execve()` like we do in POSIX environments..

**Comment by doawoo** [comment]
Update: got a fix, just pushed the commit to the `main` branch directly 🤫

**Comment by adamzaninovich** [comment]
That worked! Thanks again, @doawoo!
