### ISSUE TITLE
[FEATURE] More maintenance commands

### ISSUE THREAD

**Issue by brooksmtownsend** [burrito-elixir/burrito#91]
Hi!

Opening a blank issue in favor of a bug report, so please let me know if I should go about a different avenue to request this. I noticed that there's a placeholder for maintenance commands, and I'd love to add to that list!

In addition to `uninstall`, there's a few that I think would be super handy to be able to check when executing the burrito.
1. `install` - Simply unpack the tarball without running the application, could be nice for things like Docker images in order to unpack the contents while building the image
2. `directory` - Outputs the installed directory (if the application is unpacked somewhere) or perhaps the predicted install directory
3. `version` - Outputs the version of the embedded ERTS and the application version, which would be nice to check to see what we have installed. I know burritos upgrade automatically, so this one is a little more optional
4. ???

If there's an easy way to retrieve this information at runtime when you have a burrito, let me know! I can see some of this build metadata in the `maintenance` output, so I figured some of these helpers would be quick wins to easily output this info.

**Comment by brooksmtownsend** [comment]
The highest priority thing that I'd love to be able to fetch easily is the install directory. On Mac, when `uninstall`ing after I say "yes" I can see
```
[w] This will uninstall the application runtime for this Burrito binary!
[?] Please confirm this action [y/n]: y
[i] Deleting directory: /Users/brooks/Library/Application Support/.burrito/wasmcloud_host_erts-13.2.1_0.62.1
[i] Uninstall complete!
```

But I'd love to be able to fetch this information without uninstalling so I could know the path to the unpacked app

**Comment by doawoo** [comment]
These are excellent ideas! 
I could see a `meta` command to output the metadata in JSON straight to stdout so it can be parsed by machine or human with `jq` etc.

**Comment by brooksmtownsend** [comment]
> I could see a meta command to output the metadata in JSON straight to stdout so it can be parsed by machine or human with jq etc.

This would be _awesome_.

**Comment by doawoo** [comment]
I just pushed up 2 new maintenance commands:

`directory` - Will print the computed install path to be used when installing/uninstalling the wrapped application.

![image](https://github.com/burrito-elixir/burrito/assets/61982076/f863090a-9731-4e02-8861-d7feb682664b)


`meta` - Prints the JSON metadata which is generated at compile/wrap time, this includes compile options, release options, versions, etc.

![image](https://github.com/burrito-elixir/burrito/assets/61982076/7286fcd6-a877-4483-81bb-f6fa7192bfae)

**Comment by brooksmtownsend** [comment]
@doawoo 😲 🚀 This is awesome!!

**Comment by doawoo** [comment]
Going to close this issue for now, I'm working on re-writing the wrapper binary in Rust, which will hopefully promote some more contributions to add even more commands from folks! 😄 

This was a great issue to have some discussion on the state of the maintenance commands, thanks!

**Comment by brooksmtownsend** [comment]
Thank you @doawoo 🚀
