### ISSUE TITLE
OTP-25.3.2 Requires CDN Release

### ISSUE THREAD

**Issue by awill1988** [burrito-elixir/burrito#92]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: [macOS 12.6.5 (21G531)](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md)
**Host CPU**: amd64 (I think?)

Please run `zig version` in your Burrito project directory and write the version here:

0.10.1

Please run `elixir -v` in your Burrito project directory and write the version here:

------
```
Erlang/OTP 25 [erts-13.2.1] [source] [64-bit] [smp:3:3] [ds:3:3:10] [async-threads:1] [jit:ns] [dtrace]

Elixir 1.14.4 (compiled with Erlang/OTP 25)
0.10.1
xz (XZ Utils) 5.4.3
liblzma 5.4.3
```
### Target

**Host OS**: (all)
**Host CPU**: (all)
**Host LibC and Version** (gnu)

------

👋, thank you for this project.

I have been hitting head against a wall and I finally popped open the zig code and read error messages, etc., and wallah.

This also fails if you attempt to wrap using any of the official Docker images that pin to OTP 25.. 😔

I am simply following some instructions based on an error message and I am hoping I am filing in the right place...

```
[/otp_25.3.2_darwin_aarch64_ssl_1.1.1s.tar.gz?please-respect-my-bandwidth-costs=thank-you](https://burrito-otp.b-cdn.net/OTP-25.3.2/darwin/aarch64/otp_25.3.2_darwin_aarch64_ssl_1.1.1s.tar.gz?please-respect-my-bandwidth-costs=thank-you)
** (RuntimeError) Failed to fetch https://burrito-otp.b-cdn.net/OTP-25.3.2/darwin/aarch64/otp_25.3.2_darwin_aarch64_ssl_1.1.1s.tar.gz?please-respect-my-bandwidth-costs=thank-you! (Got 404) Perhaps we haven't built a pre-compiled Erlang for this release yet? If this was a 404, please file an issue! Thanks!
```

I think in order for this to work with the latest versions of OTP, you would need to release version `OTP-25.3.2`, correct?

Appreciate your time!

**Comment by doawoo** [comment]
Just uploaded them, try again and it should work! Re-open if you experience the issue again :)

Also note: working on OTP-26.0 as well, running into some issues with it at the moment
