### ISSUE TITLE
It seems cross-compiling works on Apple Silicon now?

### ISSUE THREAD

**Issue by arjunbajaj** [burrito-elixir/burrito#95]
### Host

**Host OS**: `MacOS 13.5`
**Host CPU**: `arm64`

```
zig version
0.10.1
```

```
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.15.4 (compiled with Erlang/OTP 26)
```

------

### Target

**Target OS**: `Alpine Linux v3.18`
**Target CPU**: `x86_64`
**Target LibC and Version**: `musl 1.2.4-r1`

------

Hi,

I am trying to use Burrito to simplify deployments of my Elixir app. I created a default Phoenix app and added Burrito to it. The readme says that cross-compiling does not work on Apple Silicon, however, that does not seem to be the case any longer.

I tried building for Alpine Linux with Zig 0.10.1, and it seems it does work. I ran the binary on `Alpine Linux v3.18 x86_64` on DigitalOcean and it seems to work.

I then tried cross-compiling for Linux x64 with glibc and MacOS x64, and they also compile successfully.

Here is the result of `file burrito_out/*`:

```
alpine:  ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
linux:   ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.0.0, stripped
mac_arm: Mach-O 64-bit executable arm64
mac_x86: Mach-O 64-bit executable x86_64
```

I suppose the main reason these are compiling now on the M1 is because of the [BEAM Machine](https://beammachine.cloud) static ERTS.

My question is, is it safe to now assume that cross-compiling from Apple Silicon produces the same result as compiling on the target OS directly?

And if cross-compiling now works on Apple Silicon, perhaps the readme should be updated?

Thanks!

**Comment by mhanberg** [comment]
I'm not sure this is a bug, but yes, you can cross compile from apple silicon to Linux arm/amd, mac amd, and windows amd.

**Comment by arjunbajaj** [comment]
Yeah sorry about the `bug` label. I realized it after posting and couldn't change it.

Thanks for the reply! That's great!
