### ISSUE TITLE
debug flag seems to be only respected on MIX_ENV=prod

### ISSUE THREAD

**Issue by karmajunkie** [burrito-elixir/burrito#96]
### Host

Tell us about your Host OS (the machine you're building burrito apps on)

**Host OS**: MacOS 13.5 Ventura
**Host CPU**: arm64 (apple silicon)

Please run `zig version` in your Burrito project directory and write the version here:
0.10.1

Please run `elixir -v` in your Burrito project directory and write the version here:
1.15.3
------

### Target

**Host OS**: MacOS 13.5 Ventura
**Host CPU**: arm64 (Apple silicon)
**Host LibC and Version** unclear and I don't know how to check this

------

When I build with the following `releases` function, I get debug build regardless of the value of the `debug` key unless `MIX_ENV=prod`. 

```
  def releases do
    [
      cli: [
        steps: [:assemble, &Burrito.wrap/1],
        burrito: [
          debug: false,
          targets: [         
            m1: [os: :darwin, cpu: :aarch64]
          ]
        ]
      ]
    ]
  end
```

I'm using this command to build: `BURRITO_TARGET=m1 mix release --overwrite`

Am I doing something weird here or is this expected behavior?

**Comment by doawoo** [comment]
Fixed on `main` 🎉
